### ISSUE TITLE
你好偶然遇到了一个bug，这个周数异常，不应该是2021年1周-2周吗

### ISSUE THREAD

**Issue by zdjzpg** [xiaofan9/date-week-range#11]
![Z%4{4T)B133HNEAZ$L_L~5V](https://user-images.githubusercontent.com/68413143/142996138-ada93106-91d7-47d1-b56d-1a0461042377.png)

**Comment by xiaofan9** [comment]
这个是什么版本？最新的版本，我已经修复了。

**Comment by zdjzpg** [comment]
> 这个是什么版本？最新的版本，我已经修复了。

你好我的版本是1.0.4，最新的是哪个版本

**Comment by xiaofan9** [comment]
> > 这个是什么版本？最新的版本，我已经修复了。
> 
> 你好我的版本是1.0.4，最新的是哪个版本
麻烦给下代码片段，我这边才能对应修复

**Comment by xiaofan9** [comment]
已经在v1.0.5 版本修复，如果还不行麻烦给下代码片段

**Comment by zdjzpg** [comment]
好的我再试试






------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "xiaofan9/date-week-range"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年12月20日(星期一) 上午10:20
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [xiaofan9/date-week-range] 你好偶然遇到了一个bug，这个周数异常，不应该是2021年1周-2周吗 (Issue #11)





 
已经在v1.0.5 版本修复，如果还不行麻烦给下代码片段
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by gongrui218** [comment]
有解决吗？用v1.0.5还是不行
