### ISSUE TITLE
value-format="yyyy-ww"

### ISSUE THREAD

**Issue by zhengbaofeng** [xiaofan9/date-week-range#3]
返回值可以返回周数吗。

**Comment by xiaofan9** [comment]
之前的版本多不行，最新的v1.0.4-beta.02已经修复了这个问题。
但需要这样value-format="yyyy-WW"

**Comment by xiaofan9** [comment]
新版本 v1.0.4 已经发布，并修复了此bug

**Comment by pbxrt** [comment]
![image](https://user-images.githubusercontent.com/22880091/120174483-b7f1d080-c237-11eb-98db-09fac1953ddc.png)
请问下，v1.0.4 发布了吗？为什么npm仓库还是没有呢？

**Comment by xiaofan9** [comment]
> ![image](https://user-images.githubusercontent.com/22880091/120174483-b7f1d080-c237-11eb-98db-09fac1953ddc.png)
> 请问下，v1.0.4 发布了吗？为什么npm仓库还是没有呢？

![image](https://user-images.githubusercontent.com/16103130/120175757-1e2b2300-c239-11eb-85dc-446f126f329d.png)
确实是发布了

**Comment by pbxrt** [comment]
> > ![image](https://user-images.githubusercontent.com/22880091/120174483-b7f1d080-c237-11eb-98db-09fac1953ddc.png)
> > 请问下，v1.0.4 发布了吗？为什么npm仓库还是没有呢？
> 
> ![image](https://user-images.githubusercontent.com/16103130/120175757-1e2b2300-c239-11eb-85dc-446f126f329d.png)
> 确实是发布了

知道了，是公司自建的仓库没有同步过来，感谢回复
