### ISSUE TITLE
你好还发现一个问题 就是当我用moment.js 设置开始时间和结束时间 展开以后结束时间定位不到选的日期

### ISSUE THREAD

**Issue by yehoan** [xiaofan9/date-week-range#7]
详情看代码https://codepen.io/xiaofan9/pen/jOByExo

**Comment by yehoan** [comment]
![image](https://user-images.githubusercontent.com/22631753/135418669-3941874b-d32d-49b4-89d5-cfcbe70f3951.png)
好像没法做到匹配

**Comment by yehoan** [comment]
你好？

**Comment by xiaofan9** [comment]
好的，预估这周完成这些修复。最近太忙了，抱歉

**Comment by xiaofan9** [comment]
> ![image](https://user-images.githubusercontent.com/22631753/135418669-3941874b-d32d-49b4-89d5-cfcbe70f3951.png) 好像没法做到匹配

已经发布v1.0.5，你试试，要是还不行就麻烦你把代码片段贴上来，我这边测试下
